apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-green
  namespace: {{ .Values.namespace   }}
data:
  delivery-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: {{ .Values.cluster }}
    service: delivery
    shard: green
    customTags:
      location: {{ .Values.customtags.location }}
      env: {{ .Values.customtags.environment }}

  delivery-app.yml: |
    server:
      port: 50054
    
    notificationHost: notification
    notificationPort: 50056
    
    applicationTagsYamlFile: "/conf/delivery-app-tags.yaml"
    wfReportingConfigYamlFile: "/conf/wf-config.yaml"

  inventory.conf: |
    {
    	"application": "{{ include "tanzu-observability-demo.fullname" .  }}",
    	"service":     "inventory",
    	"cluster":     "{{ .Values.cluster }}",
    	"shard":       "green",	
    
    	"inventoryHost": "0.0.0.0:60001",
    	"warehouseHost": "warehouse:50060",
    
    	"proxyHost":              "{{ .Values.namespace   }}-wavefront-proxy",
    	"proxyPort":              2878,
    	"proxyDistributionsPort": 40000,
    	"proxyTracingPort":       30000,
    
    	"simFailCheckout":  0.02,
    	"simFailAvailable": 0.03,
    	"simDelayChance":   0.3333,
    	"simDelayMS":       1000,
    	"simDelayCpuPct":   0.4
    }

  notification-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: {{ .Values.cluster }}
    service: notification
    shard: green
    customTags:
      location: {{ .Values.customtags.location }}
      env: {{ .Values.customtags.environment }}

  notification-app.yml: |
    server:
      port: 50056
    
    cxf:
      path: /
      jaxrs:
        component-scan: true
    
    applicationTagsYamlFile: "/conf/notification-app-tags.yaml"
    wfReportingConfigYamlFile: "/conf/wf-config.yaml"


  packaging-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: {{ .Values.cluster }}
    service: packaging
    shard: green
    customTags:
      location: {{ .Values.customtags.location }}
      env: {{ .Values.customtags.environment }}

  packaging-app.yaml: |
    grpcPort: 50053
    applicationTagsYamlFile: "/conf/packaging-app-tags.yaml"
    wfReportingConfigYamlFile: "/conf/wf-config.yaml"

  payments-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: {{ .Values.cluster }}
    service: payments
    shard: green
    customTags:
      location: {{ .Values.customtags.location }}
      env: {{ .Values.customtags.environment }}


  payments-app.yaml: |
    port: 50063
    applicationTagsYamlFile: "/conf/payments-app-tags.yaml"
    wfReportingConfigYamlFile: "/conf/wf-config.yaml"


  printing-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: {{ .Values.cluster }}
    service: printing
    shard: green
    customTags:
      location: {{ .Values.customtags.location }}
      env: {{ .Values.customtags.environment }}


  printing-app.yaml: |
    grpcPort: 50052
    applicationTagsYamlFile: "/conf/printing-app-tags.yaml"
    wfReportingConfigYamlFile: "/conf/wf-config.yaml"

  shopping-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: {{ .Values.cluster }}
    service: shopping
    shard: green
    customTags:
      location: {{ .Values.customtags.location }}
      env: {{ .Values.customtags.environment }}

  shopping-app.yaml: |
    server:
      applicationConnectors:
      - type: http
        port: 50050
      adminConnectors:
      - type: http
        port: 50150
    
    inventoryPort: 60001
    paymentsPort: 50063
    stylingPort: 50051
    deliveryPort: 50054
    
    inventoryHost: "inventory"
    paymentsHost: "payments"
    stylingHost: "styling"
    deliveryHost: "delivery"
    
    applicationTagsYamlFile: "/conf/shopping-app-tags.yaml"
    wfReportingConfigYamlFile: "/conf/wf-config.yaml"

  shop-ui-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: to-cp-demo-cluster-12
    service: shop-ui
    shard: green
    customTags:
      location: eks
      env: {{ .Values.customtags.environment }}
    server:
      applicationConnectors:
      - type: http
      port: 8080

  styling-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: {{ .Values.cluster }}
    service: styling
    shard: green
    customTags:
      location: {{ .Values.customtags.location }}
      env: {{ .Values.customtags.environment }}

  styling-app.yaml: |
    server:
      applicationConnectors:
      - type: http
        port: 50051
      adminConnectors:
      - type: http
        port: 50151
    
    inventoryPort: 60001
    printingPort: 50052
    packagingPort: 50053
    shoppingPort: 50050
    
    inventoryHost: "inventory"
    printingHost: "printing"
    packagingHost: "packaging"
    shoppingHost: "shopping"
    
    applicationTagsYamlFile: "/conf/styling-app-tags.yaml"
    wfReportingConfigYamlFile: "/conf/wf-config.yaml"

  warehouse-app-tags.yaml: |
    application: {{ include "tanzu-observability-demo.fullname" .  }}
    cluster: {{ .Values.cluster }}
    service: warehouse
    shard: green
    customTags:
      location: {{ .Values.customtags.location }}
      env: {{ .Values.customtags.environment }}


  wf-config.yaml: |
    reportingMechanism: proxy
    proxyHost: {{ .Values.namespace   }}-wavefront-proxy
    proxyMetricsPort: 2878
    proxyDistributionsPort: 2878
    proxyTracingPort: 30000
    
    reportTraces: true


