apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: styling
    shard: blue
  name: styling-blue
  namespace: {{ .Values.namespace   }}
spec:
  replicas: {{ .Values.replicaCount.blue  }}
  selector:
    matchLabels:
      app: {{ include "tanzu-observability-demo.fullname" .  }}
      service: styling
      shard: blue
  template:
    metadata:
      labels:
        app: {{ include "tanzu-observability-demo.fullname" .  }}
        service: styling
        shard: blue
    spec:
      containers:
      - name: styling
        image: {{ .Values.image.repository }}/styling:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-jar"
        - "/styling.jar"
        - "server"
        - "/conf/styling-app.yaml"
        ports:
        - containerPort: 50051
          name: application
          protocol: TCP
        - containerPort: 50151
          name: admin
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: styling
    shard: green
  name: styling-green
  namespace: {{ .Values.namespace   }}
spec:
  replicas: {{ .Values.replicaCount.green  }}
  selector:
    matchLabels:
      app: {{ include "tanzu-observability-demo.fullname" .  }}
      service: styling
      shard: green
  template:
    metadata:
      labels:
        app: {{ include "tanzu-observability-demo.fullname" .  }}
        service: styling
        shard: green
    spec:
      containers:
        - name: styling
          image: {{ .Values.image.repository }}/styling:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/styling.jar"
            - "server"
            - "/conf/styling-app.yaml"
          ports:
            - containerPort: 50051
              name: application
              protocol: TCP
            - containerPort: 50151
              name: admin
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: styling
  namespace: {{ .Values.namespace   }}
spec: 
  selector:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: styling  
  type: ClusterIP
  ports:
  - name: application
    port: 50051
  - name: admin
    port: 50151

