apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: printing
    shard: blue
  name: printing-blue
  namespace: {{ .Values.namespace   }}
spec:
  replicas: {{ .Values.replicaCount.blue  }}
  selector:
    matchLabels:
      app: {{ include "tanzu-observability-demo.fullname" .  }}
      service: printing
      shard: blue
  template:
    metadata:
      labels:
        app: {{ include "tanzu-observability-demo.fullname" .  }}
        service: printing
        shard: blue
    spec:
      containers:
      - name: printing
        image: {{ .Values.image.repository }}/printing:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-jar"
        - "/printing.jar"
        - "/conf/printing-app.yaml"
        ports:
        - containerPort: 50052
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: printing
    shard: green
  name: printing-green
  namespace: {{ .Values.namespace   }}
spec:
  replicas: {{ .Values.replicaCount.green  }}
  selector:
    matchLabels:
      app: {{ include "tanzu-observability-demo.fullname" .  }}
      service: printing
      shard: green
  template:
    metadata:
      labels:
        app: {{ include "tanzu-observability-demo.fullname" .  }}
        service: printing
        shard: green
    spec:
      containers:
        - name: printing
          image: {{ .Values.image.repository }}/printing:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/printing.jar"
            - "/conf/printing-app.yaml"
          ports:
            - containerPort: 50052
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: printing
  namespace: {{ .Values.namespace   }}
spec: 
  selector:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: printing
  type: ClusterIP
  ports:
  - name: application
    port: 50052
