apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: payments
    shard: blue
  name: payments-blue
  namespace: tacocat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacocat
      service: payments
      shard: blue
  template:
    metadata:
      labels:
        app: tacocat
        service: payments
        shard: blue
    spec:
      containers:
      - name: payments
        image: 192.168.1.8/demo-app/payments:latest
        imagePullPolicy: Always
        command:
        - "dotnet"
        - "run"
        - "-p"
        - "/payments/src/Payments/"
        ports:
        - containerPort: 50063
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: payments
    shard: green
  name: payments-green
  namespace: tacocat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacocat
      service: payments
      shard: green
  template:
    metadata:
      labels:
        app: tacocat
        service: payments
        shard: green
    spec:
      containers:
        - name: payments
          image: 192.168.1.8/demo-app/payments:latest
          imagePullPolicy: Always
          command:
            - "dotnet"
            - "run"
            - "-p"
            - "/payments/src/Payments/"
          ports:
            - containerPort: 50063
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: tacocat
spec: 
  selector:
    app: tacocat
    service: payments
  type: ClusterIP
  ports:
  - name: application
    port: 50063

