apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: inventory
    shard: blue
  name: inventory-blue
  namespace: tacocat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tacocat
      service: inventory
      shard: blue
  template:
    metadata:
      labels:
        app: tacocat
        service: inventory
        shard: blue
    spec:
      containers:
      - name: inventory
        image: 192.168.1.8/demo-app/inventory:latest
        imagePullPolicy: Always
        command:
        - "/inventory"
        - "/conf/inventory.conf"
        ports:
        - containerPort: 60001
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: inventory
    shard: green
  name: inventory-green
  namespace: tacocat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tacocat
      service: inventory
      shard: green
  template:
    metadata:
      labels:
        app: tacocat
        service: inventory
        shard: green
    spec:
      containers:
        - name: inventory
          image: 192.168.1.8/demo-app/inventory:latest
          imagePullPolicy: Always
          command:
            - "/inventory"
            - "/conf/inventory.conf"
          ports:
            - containerPort: 60001
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: tacocat
spec: 
  selector:
    app: tacocat
    service: inventory  
  type: ClusterIP
  ports:
  - name: application
    port: 60001

