apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: loadgen
  name: loadgen
  namespace: tacocat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacocat
      service: loadgen
  template:
    metadata:
      labels:
        app: tacocat
        service: loadgen
    spec:
      containers:
      - name: loadgen
        image: 192.168.1.8/demo-app/loadgen:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-jar"
        - "/loadgen.jar"
        - "shopping"
        - "50050"
        - "50051"
        - "2"
        - "15"
        - "0"
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
