# Need to change YOUR_CLUSTER and YOUR_API_TOKEN accordingly

apiVersion: apps/v1
# Kubernetes versions after 1.9.0 should use apps/v1
# Kubernetes version 1.8.x should use apps/v1beta2
# Kubernetes versions before 1.8.0 should use apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: wavefront-proxy
    name: sandbox-wavefront-proxy
  name: sandbox-wavefront-proxy
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavefront-proxy
  template:
    metadata:
      labels:
        app: wavefront-proxy
    spec:
      containers:
      - name: sandbox-wavefront-proxy
        image: wavefronthq/proxy:9.1
        imagePullPolicy: IfNotPresent
        env:
        - name: WAVEFRONT_URL
          value: https://longboard.wavefront.com/api/
        - name: WAVEFRONT_TOKEN
          valueFrom:
            secretKeyRef:
              name: wf-token
              key: token
        # Uncomment the below lines to consume Zipkin/Istio traces
        - name: WAVEFRONT_PROXY_ARGS
          value: --traceListenerPorts 30000
        ports:
        - containerPort: 2878
          protocol: TCP
        # Uncomment the below lines to consume traces
        - containerPort: 30000
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-wavefront-proxy
  labels:
    app: wavefront-proxy
  namespace: sandbox
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  - name: http
    port: 30000
    targetPort: 30000
    protocol: TCP
  selector:
    app: wavefront-proxy
